
[package]
name = "portfolio-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
yahoo_finance_api = "1.3"
crossterm = "0.25"
tui = "0.19"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
